import mods.extendedcrafting.TableCrafting;

mods.extendedcrafting.TableCrafting.addShaped("creative_essence", 4, <item:mysticalagradditions:creative_essence>, [
	[<item:mysticalagriculture:supremium_essence>, <item:mysticalagriculture:supremium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagriculture:supremium_essence>, <item:mysticalagriculture:supremium_essence>], 
	[<item:mysticalagriculture:supremium_essence>, <item:forbidden_arcanus:dragon_scale>, <item:forbidden_arcanus:dragon_scale>, <item:occultism:spirit_attuned_gem>, <item:extendedcrafting:nether_star_block>, <item:occultism:spirit_attuned_gem>, <item:forbidden_arcanus:dragon_scale>, <item:forbidden_arcanus:dragon_scale>, <item:mysticalagriculture:supremium_essence>], 
	[<item:mysticalagradditions:insanium_essence>, <item:forbidden_arcanus:dragon_scale>, <item:minecraft:enchanted_golden_apple>, <item:forbidden_arcanus:mundabitur_dust>, <item:extendedcrafting:nether_star_block>, <item:forbidden_arcanus:mundabitur_dust>, <item:minecraft:enchanted_golden_apple>, <item:forbidden_arcanus:dragon_scale>, <item:mysticalagradditions:insanium_essence>], 
	[<item:mysticalagradditions:insanium_essence>, <item:advanced_ae:quantum_infused_dust>, <item:forbidden_arcanus:mundabitur_dust>, <item:forbidden_arcanus:eternal_stella>, <item:mysticalagriculture:awakened_supremium_essence>, <item:forbidden_arcanus:eternal_stella>, <item:forbidden_arcanus:mundabitur_dust>, <item:advanced_ae:quantum_infused_dust>, <item:mysticalagradditions:insanium_essence>], 
	[<item:mysticalagradditions:insanium_essence>, <item:extendedcrafting:nether_star_block>, <item:extendedcrafting:nether_star_block>, <item:mysticalagriculture:awakened_supremium_essence>, <item:mysticalagriculture:awakened_supremium_essence>, <item:mysticalagriculture:awakened_supremium_essence>, <item:extendedcrafting:nether_star_block>, <item:extendedcrafting:nether_star_block>, <item:mysticalagradditions:insanium_essence>], 
	[<item:mysticalagradditions:insanium_essence>, <item:advanced_ae:quantum_infused_dust>, <item:forbidden_arcanus:mundabitur_dust>, <item:forbidden_arcanus:eternal_stella>, <item:mysticalagriculture:awakened_supremium_essence>, <item:forbidden_arcanus:eternal_stella>, <item:forbidden_arcanus:mundabitur_dust>, <item:advanced_ae:quantum_infused_dust>, <item:mysticalagradditions:insanium_essence>], 
	[<item:mysticalagradditions:insanium_essence>, <item:forbidden_arcanus:dragon_scale>, <item:minecraft:enchanted_golden_apple>, <item:forbidden_arcanus:mundabitur_dust>, <item:extendedcrafting:nether_star_block>, <item:forbidden_arcanus:mundabitur_dust>, <item:minecraft:enchanted_golden_apple>, <item:forbidden_arcanus:dragon_scale>, <item:mysticalagradditions:insanium_essence>], 
	[<item:mysticalagriculture:supremium_essence>, <item:forbidden_arcanus:dragon_scale>, <item:forbidden_arcanus:dragon_scale>, <item:occultism:spirit_attuned_gem>, <item:extendedcrafting:nether_star_block>, <item:occultism:spirit_attuned_gem>, <item:forbidden_arcanus:dragon_scale>, <item:forbidden_arcanus:dragon_scale>, <item:mysticalagriculture:supremium_essence>], 
	[<item:mysticalagriculture:supremium_essence>, <item:mysticalagriculture:supremium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagriculture:supremium_essence>, <item:mysticalagriculture:supremium_essence>]
]); 

mods.extendedcrafting.TableCrafting.addShaped("ultimate_ingot", 4, <item:extendedcrafting:the_ultimate_ingot>, [
	[<item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:ultimate_singularity>], 
	[<item:extendedcrafting:crystaltine_ingot>, <item:mysticalagradditions:creative_essence>, <item:botania:terrasteel_ingot>, <item:botania:terrasteel_ingot>, <item:botania:terrasteel_ingot>, <item:botania:terrasteel_ingot>, <item:botania:terrasteel_ingot>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:crystaltine_ingot>], 
	[<item:extendedcrafting:crystaltine_ingot>, <item:botania:terrasteel_ingot>, <item:draconicevolution:awakened_draconium_block>, <item:bloodmagic:etherealslate>, <item:ars_elemental:air_focus>, <item:bloodmagic:etherealslate>, <item:draconicevolution:awakened_draconium_block>, <item:botania:terrasteel_ingot>, <item:extendedcrafting:crystaltine_ingot>], 
	[<item:extendedcrafting:crystaltine_ingot>, <item:botania:terrasteel_ingot>, <item:bloodmagic:etherealslate>, <item:draconicevolution:awakened_draconium_block>, <item:apotheosis:mythic_material>, <item:draconicevolution:awakened_draconium_block>, <item:bloodmagic:etherealslate>, <item:botania:terrasteel_ingot>, <item:extendedcrafting:crystaltine_ingot>], 
	[<item:extendedcrafting:crystaltine_ingot>, <item:botania:terrasteel_ingot>, <item:ars_elemental:water_focus>, <item:apotheosis:mythic_material>, <item:ars_elemental:necrotic_focus>, <item:apotheosis:mythic_material>, <item:ars_elemental:earth_focus>, <item:botania:terrasteel_ingot>, <item:extendedcrafting:crystaltine_ingot>], 
	[<item:extendedcrafting:crystaltine_ingot>, <item:botania:terrasteel_ingot>, <item:bloodmagic:etherealslate>, <item:draconicevolution:awakened_draconium_block>, <item:apotheosis:mythic_material>, <item:draconicevolution:awakened_draconium_block>, <item:bloodmagic:etherealslate>, <item:botania:terrasteel_ingot>, <item:extendedcrafting:crystaltine_ingot>], 
	[<item:extendedcrafting:crystaltine_ingot>, <item:botania:terrasteel_ingot>, <item:draconicevolution:awakened_draconium_block>, <item:bloodmagic:etherealslate>, <item:ars_elemental:fire_focus>, <item:bloodmagic:etherealslate>, <item:draconicevolution:awakened_draconium_block>, <item:botania:terrasteel_ingot>, <item:extendedcrafting:crystaltine_ingot>], 
	[<item:extendedcrafting:crystaltine_ingot>, <item:mysticalagradditions:creative_essence>, <item:botania:terrasteel_ingot>, <item:botania:terrasteel_ingot>, <item:botania:terrasteel_ingot>, <item:botania:terrasteel_ingot>, <item:botania:terrasteel_ingot>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:crystaltine_ingot>], 
	[<item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:ultimate_singularity>]
]);

mods.extendedcrafting.TableCrafting.addShaped("the_everlasting_guilty_pool", 4, <item:botania:creative_pool>, [
	[<item:mythicbotany:alfsteel_ingot>, <item:ars_nouveau:air_essence>, <item:ars_nouveau:air_essence>, <item:ars_nouveau:air_essence>, <item:draconicevolution:chaotic_core>, <item:ars_nouveau:air_essence>, <item:ars_nouveau:air_essence>, <item:ars_nouveau:air_essence>, <item:mythicbotany:alfsteel_ingot>], 
	[<item:ars_nouveau:earth_essence>, <item:mythicbotany:alfsteel_ingot>, <item:bloodmagic:etherealslate>, <item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_block>, <item:bloodmagic:etherealslate>, <item:mythicbotany:alfsteel_ingot>, <item:ars_nouveau:abjuration_essence>], 
	[<item:ars_nouveau:earth_essence>, <item:apotheosis:infused_breath>, <item:mythicbotany:alfsteel_ingot>, <item:mysticalagradditions:insanium_block>, <item:advanced_ae:quantum_storage_component>, <item:mysticalagradditions:insanium_block>, <item:mythicbotany:alfsteel_ingot>, <item:apotheosis:infused_breath>, <item:ars_nouveau:abjuration_essence>], 
	[<item:ars_nouveau:earth_essence>, <item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_block>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:ultimate_singularity>, <item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_block>, <item:ars_nouveau:abjuration_essence>], 
	[<item:draconicevolution:chaotic_core>, <item:mysticalagradditions:insanium_block>, <item:advanced_ae:quantum_storage_component>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:the_ultimate_block>, <item:extendedcrafting:ultimate_singularity>, <item:advanced_ae:quantum_storage_component>, <item:mysticalagradditions:insanium_block>, <item:draconicevolution:chaotic_core>], 
	[<item:ars_nouveau:earth_essence>, <item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_block>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:ultimate_singularity>, <item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_block>, <item:ars_nouveau:abjuration_essence>], 
	[<item:ars_nouveau:earth_essence>, <item:apotheosis:infused_breath>, <item:mythicbotany:alfsteel_ingot>, <item:mysticalagradditions:insanium_block>, <item:advanced_ae:quantum_storage_component>, <item:mysticalagradditions:insanium_block>, <item:mythicbotany:alfsteel_ingot>, <item:apotheosis:infused_breath>, <item:ars_nouveau:abjuration_essence>], 
	[<item:ars_nouveau:earth_essence>, <item:mythicbotany:alfsteel_ingot>, <item:bloodmagic:etherealslate>, <item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_block>, <item:bloodmagic:etherealslate>, <item:mythicbotany:alfsteel_ingot>, <item:ars_nouveau:abjuration_essence>], 
	[<item:mythicbotany:alfsteel_ingot>, <item:ars_nouveau:conjuration_essence>, <item:ars_nouveau:conjuration_essence>, <item:ars_nouveau:conjuration_essence>, <item:draconicevolution:chaotic_core>, <item:ars_nouveau:conjuration_essence>, <item:ars_nouveau:conjuration_essence>, <item:ars_nouveau:conjuration_essence>, <item:mythicbotany:alfsteel_ingot>]
]);

mods.extendedcrafting.TableCrafting.addShaped("creative_tablet", 4, <item:botania:mana_tablet>.withTag({mana: 500000, creative: 1}), [
	[<item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_block>, <item:bloodmagic:etherealslate>, <item:bloodmagic:etherealslate>, <item:extendedcrafting:ultimate_singularity>, <item:bloodmagic:etherealslate>, <item:bloodmagic:etherealslate>, <item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_block>], 
	[<item:mysticalagradditions:insanium_block>, <item:mythicbotany:joetunheim_rune>, <item:draconicevolution:awakened_draconium_block>, <item:mythicbotany:alfheim_rune>, <item:extendedcrafting:ultimate_singularity>, <item:mythicbotany:alfheim_rune>, <item:draconicevolution:awakened_draconium_block>, <item:mythicbotany:niflheim_rune>, <item:mysticalagradditions:insanium_block>], 
	[<item:bloodmagic:etherealslate>, <item:draconicevolution:awakened_draconium_block>, <item:mythicbotany:midgard_rune>, <item:extendedcrafting:flux_star>, <item:mythicbotany:alfsteel_ingot>, <item:extendedcrafting:flux_star>, <item:mythicbotany:muspelheim_rune>, <item:draconicevolution:awakened_draconium_block>, <item:bloodmagic:etherealslate>], 
	[<item:bloodmagic:etherealslate>, <item:mythicbotany:alfheim_rune>, <item:extendedcrafting:ender_star>, <item:mythicbotany:alfsteel_ingot>, <item:mythicbotany:alfsteel_ingot>, <item:mythicbotany:alfsteel_ingot>, <item:extendedcrafting:ender_star>, <item:mythicbotany:alfheim_rune>, <item:bloodmagic:etherealslate>], 
	[<item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:ultimate_singularity>, <item:mythicbotany:alfsteel_ingot>, <item:mythicbotany:alfsteel_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:mythicbotany:alfsteel_ingot>, <item:mythicbotany:alfsteel_ingot>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:ultimate_singularity>], 
	[<item:bloodmagic:etherealslate>, <item:mythicbotany:alfheim_rune>, <item:extendedcrafting:ender_star>, <item:mythicbotany:alfsteel_ingot>, <item:mythicbotany:alfsteel_ingot>, <item:mythicbotany:alfsteel_ingot>, <item:extendedcrafting:ender_star>, <item:mythicbotany:alfheim_rune>, <item:bloodmagic:etherealslate>], 
	[<item:bloodmagic:etherealslate>, <item:draconicevolution:awakened_draconium_block>, <item:mythicbotany:asgard_rune>, <item:extendedcrafting:flux_star>, <item:mythicbotany:alfsteel_ingot>, <item:extendedcrafting:flux_star>, <item:mythicbotany:nidavellir_rune>, <item:draconicevolution:awakened_draconium_block>, <item:bloodmagic:etherealslate>], 
	[<item:mysticalagradditions:insanium_block>, <item:mythicbotany:helheim_rune>, <item:draconicevolution:awakened_draconium_block>, <item:mythicbotany:alfheim_rune>, <item:extendedcrafting:ultimate_singularity>, <item:mythicbotany:alfheim_rune>, <item:draconicevolution:awakened_draconium_block>, <item:mythicbotany:vanaheim_rune>, <item:mysticalagradditions:insanium_block>], 
	[<item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_block>, <item:bloodmagic:etherealslate>, <item:bloodmagic:etherealslate>, <item:extendedcrafting:ultimate_singularity>, <item:bloodmagic:etherealslate>, <item:bloodmagic:etherealslate>, <item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_block>]
]);

mods.extendedcrafting.TableCrafting.addShaped("draconic_injector", 3, <item:draconicevolution:basic_crafting_injector>, [
	[<item:extendedcrafting:flux_star_block>, <item:extendedcrafting:flux_star_block>, <item:extendedcrafting:ender_star_block>, <item:extendedcrafting:ender_star_block>, <item:extendedcrafting:ender_star_block>, <item:extendedcrafting:flux_star_block>, <item:extendedcrafting:flux_star_block>], 
	[<item:extendedcrafting:flux_star_block>, <item:minecraft:end_crystal>, <item:mekanism:alloy_atomic>, <item:enderio:vibrant_alloy_block>, <item:mekanism:alloy_atomic>, <item:minecraft:end_crystal>, <item:extendedcrafting:flux_star_block>], 
	[<item:extendedcrafting:ender_star_block>, <item:mekanism:alloy_atomic>, <item:draconicevolution:wyvern_core>, <item:enderio:vibrant_alloy_block>, <item:draconicevolution:wyvern_core>, <item:mekanism:alloy_atomic>, <item:extendedcrafting:ender_star_block>], 
	[<item:extendedcrafting:ender_star_block>, <item:enderio:vibrant_alloy_block>, <item:enderio:vibrant_alloy_block>, <item:bigreactors:blutonium_block>, <item:enderio:vibrant_alloy_block>, <item:enderio:vibrant_alloy_block>, <item:extendedcrafting:ender_star_block>], 
	[<item:extendedcrafting:ender_star_block>, <item:mekanism:alloy_atomic>, <item:draconicevolution:wyvern_core>, <item:enderio:vibrant_alloy_block>, <item:draconicevolution:wyvern_core>, <item:mekanism:alloy_atomic>, <item:extendedcrafting:ender_star_block>], 
	[<item:extendedcrafting:flux_star_block>, <item:minecraft:end_crystal>, <item:mekanism:alloy_atomic>, <item:enderio:vibrant_alloy_block>, <item:mekanism:alloy_atomic>, <item:minecraft:end_crystal>, <item:extendedcrafting:flux_star_block>], 
	[<item:extendedcrafting:flux_star_block>, <item:extendedcrafting:flux_star_block>, <item:extendedcrafting:ender_star_block>, <item:extendedcrafting:ender_star_block>, <item:extendedcrafting:ender_star_block>, <item:extendedcrafting:flux_star_block>, <item:extendedcrafting:flux_star_block>]
]);

mods.extendedcrafting.TableCrafting.addShaped("creative_fluid_tank", 4, <item:mekanism:creative_fluid_tank>, [
	[<item:draconicevolution:awakened_draconium_block>, <item:draconicevolution:awakened_core>, <item:advanced_ae:quantum_alloy_block>, <item:ae2:singularity>, <item:extendedcrafting:ultimate_singularity>, <item:ae2:singularity>, <item:advanced_ae:quantum_alloy_block>, <item:draconicevolution:awakened_core>, <item:draconicevolution:awakened_draconium_block>], 
	[<item:draconicevolution:awakened_core>, <item:advanced_ae:quantum_alloy_plate>, <item:advanced_ae:quantum_alloy_block>, <item:industrialforegoing:supreme_black_hole_tank>, <item:industrialforegoing:supreme_black_hole_tank>, <item:industrialforegoing:supreme_black_hole_tank>, <item:advanced_ae:quantum_alloy_block>, <item:advanced_ae:quantum_alloy_plate>, <item:draconicevolution:awakened_core>], 
	[<item:advanced_ae:quantum_alloy_block>, <item:advanced_ae:quantum_alloy_block>, <item:mythicbotany:alfsteel_block>, <item:bloodmagic:etherealslate>, <item:draconicevolution:draconic_energy_core>, <item:bloodmagic:etherealslate>, <item:mythicbotany:alfsteel_block>, <item:advanced_ae:quantum_alloy_block>, <item:advanced_ae:quantum_alloy_block>], 
	[<item:ae2:singularity>, <item:industrialforegoing:supreme_black_hole_tank>, <item:bloodmagic:etherealslate>, <item:draconicevolution:draconic_energy_core>, <item:draconicevolution:draconic_energy_core>, <item:draconicevolution:draconic_energy_core>, <item:bloodmagic:etherealslate>, <item:industrialforegoing:supreme_black_hole_tank>, <item:ae2:singularity>], 
	[<item:extendedcrafting:ultimate_singularity>, <item:industrialforegoing:supreme_black_hole_tank>, <item:draconicevolution:draconic_energy_core>, <item:draconicevolution:draconic_energy_core>, <item:extendedcrafting:the_ultimate_block>, <item:draconicevolution:draconic_energy_core>, <item:draconicevolution:draconic_energy_core>, <item:industrialforegoing:supreme_black_hole_tank>, <item:extendedcrafting:ultimate_singularity>], 
	[<item:ae2:singularity>, <item:industrialforegoing:supreme_black_hole_tank>, <item:bloodmagic:etherealslate>, <item:draconicevolution:draconic_energy_core>, <item:draconicevolution:draconic_energy_core>, <item:draconicevolution:draconic_energy_core>, <item:bloodmagic:etherealslate>, <item:industrialforegoing:supreme_black_hole_tank>, <item:ae2:singularity>], 
	[<item:advanced_ae:quantum_alloy_block>, <item:advanced_ae:quantum_alloy_block>, <item:mythicbotany:alfsteel_block>, <item:bloodmagic:etherealslate>, <item:draconicevolution:draconic_energy_core>, <item:bloodmagic:etherealslate>, <item:mythicbotany:alfsteel_block>, <item:advanced_ae:quantum_alloy_block>, <item:advanced_ae:quantum_alloy_block>], 
	[<item:draconicevolution:awakened_core>, <item:advanced_ae:quantum_alloy_plate>, <item:advanced_ae:quantum_alloy_block>, <item:industrialforegoing:supreme_black_hole_tank>, <item:industrialforegoing:supreme_black_hole_tank>, <item:industrialforegoing:supreme_black_hole_tank>, <item:advanced_ae:quantum_alloy_block>, <item:advanced_ae:quantum_alloy_plate>, <item:draconicevolution:awakened_core>], 
	[<item:draconicevolution:awakened_draconium_block>, <item:draconicevolution:awakened_core>, <item:advanced_ae:quantum_alloy_block>, <item:ae2:singularity>, <item:extendedcrafting:ultimate_singularity>, <item:ae2:singularity>, <item:advanced_ae:quantum_alloy_block>, <item:draconicevolution:awakened_core>, <item:draconicevolution:awakened_draconium_block>]
]);

mods.extendedcrafting.TableCrafting.addShaped("creative_chemical_tank", 4, <item:mekanism:creative_chemical_tank>, [
	[<item:industrialforegoing:supreme_black_hole_tank>, <item:industrialforegoing:supreme_black_hole_tank>, <item:advanced_ae:quantum_alloy_block>, <item:advanced_ae:quantum_alloy_block>, <item:extendedcrafting:ultimate_singularity>, <item:advanced_ae:quantum_alloy_block>, <item:advanced_ae:quantum_alloy_block>, <item:industrialforegoing:supreme_black_hole_tank>, <item:industrialforegoing:supreme_black_hole_tank>], 
	[<item:industrialforegoing:supreme_black_hole_tank>, <item:apotheosis:sigil_of_enhancement>, <item:forbidden_arcanus:aquatic_dragon_scale>, <item:industrialforegoing:machine_frame_supreme>, <item:botania:gaia_ingot>, <item:industrialforegoing:machine_frame_supreme>, <item:forbidden_arcanus:aquatic_dragon_scale>, <item:apotheosis:sigil_of_enhancement>, <item:industrialforegoing:supreme_black_hole_tank>], 
	[<item:advanced_ae:quantum_alloy_block>, <item:forbidden_arcanus:aquatic_dragon_scale>, <item:apotheosis:sigil_of_enhancement>, <item:botania:gaia_ingot>, <item:draconicevolution:awakened_core>, <item:botania:gaia_ingot>, <item:apotheosis:sigil_of_enhancement>, <item:forbidden_arcanus:aquatic_dragon_scale>, <item:advanced_ae:quantum_alloy_block>], 
	[<item:advanced_ae:quantum_alloy_block>, <item:industrialforegoing:machine_frame_supreme>, <item:botania:gaia_ingot>, <item:advanced_ae:quantum_alloy_plate>, <item:draconicevolution:awakened_draconium_block>, <item:advanced_ae:quantum_alloy_plate>, <item:botania:gaia_ingot>, <item:industrialforegoing:machine_frame_supreme>, <item:advanced_ae:quantum_alloy_block>], 
	[<item:extendedcrafting:ultimate_singularity>, <item:botania:gaia_ingot>, <item:draconicevolution:awakened_core>, <item:draconicevolution:awakened_draconium_block>, <item:extendedcrafting:the_ultimate_block>, <item:draconicevolution:awakened_draconium_block>, <item:draconicevolution:awakened_core>, <item:botania:gaia_ingot>, <item:extendedcrafting:ultimate_singularity>], 
	[<item:advanced_ae:quantum_alloy_block>, <item:industrialforegoing:machine_frame_supreme>, <item:botania:gaia_ingot>, <item:advanced_ae:quantum_alloy_plate>, <item:draconicevolution:awakened_draconium_block>, <item:advanced_ae:quantum_alloy_plate>, <item:botania:gaia_ingot>, <item:industrialforegoing:machine_frame_supreme>, <item:advanced_ae:quantum_alloy_block>], 
	[<item:advanced_ae:quantum_alloy_block>, <item:forbidden_arcanus:aquatic_dragon_scale>, <item:apotheosis:sigil_of_enhancement>, <item:botania:gaia_ingot>, <item:draconicevolution:awakened_core>, <item:botania:gaia_ingot>, <item:apotheosis:sigil_of_enhancement>, <item:forbidden_arcanus:aquatic_dragon_scale>, <item:advanced_ae:quantum_alloy_block>], 
	[<item:industrialforegoing:supreme_black_hole_tank>, <item:apotheosis:sigil_of_enhancement>, <item:forbidden_arcanus:aquatic_dragon_scale>, <item:industrialforegoing:machine_frame_supreme>, <item:botania:gaia_ingot>, <item:industrialforegoing:machine_frame_supreme>, <item:forbidden_arcanus:aquatic_dragon_scale>, <item:apotheosis:sigil_of_enhancement>, <item:industrialforegoing:supreme_black_hole_tank>], 
	[<item:industrialforegoing:supreme_black_hole_tank>, <item:industrialforegoing:supreme_black_hole_tank>, <item:advanced_ae:quantum_alloy_block>, <item:advanced_ae:quantum_alloy_block>, <item:extendedcrafting:ultimate_singularity>, <item:advanced_ae:quantum_alloy_block>, <item:advanced_ae:quantum_alloy_block>, <item:industrialforegoing:supreme_black_hole_tank>, <item:industrialforegoing:supreme_black_hole_tank>]
]);

mods.extendedcrafting.TableCrafting.addShaped("angel_ring", 4, <item:angelring:angel_ring>, [
	[<item:botania:terrasteel_block>, <item:ae2:singularity>, <item:extendedcrafting:ender_star_block>, <item:extendedcrafting:ender_star_block>, <item:extendedcrafting:flux_star_block>, <item:extendedcrafting:ender_star_block>, <item:extendedcrafting:ender_star_block>, <item:ae2:singularity>, <item:botania:terrasteel_block>], 
	[<item:ae2:singularity>, <item:botania:terrasteel_block>, <item:advanced_ae:shattered_singularity>, <item:occultism:otherworld_essence>, <item:extendedcrafting:flux_star_block>, <item:occultism:otherworld_essence>, <item:advanced_ae:shattered_singularity>, <item:botania:terrasteel_block>, <item:ae2:singularity>], 
	[<item:extendedcrafting:ender_star_block>, <item:advanced_ae:shattered_singularity>, <item:botania:terrasteel_block>, <item:occultism:otherworld_essence>, <item:extendedcrafting:flux_star_block>, <item:occultism:otherworld_essence>, <item:botania:terrasteel_block>, <item:advanced_ae:shattered_singularity>, <item:extendedcrafting:ender_star_block>], 
	[<item:extendedcrafting:ender_star_block>, <item:occultism:otherworld_essence>, <item:occultism:otherworld_essence>, <item:botania:gaia_ingot>, <item:botania:gaia_ingot>, <item:botania:gaia_ingot>, <item:occultism:otherworld_essence>, <item:occultism:otherworld_essence>, <item:extendedcrafting:ender_star_block>], 
	[<item:extendedcrafting:flux_star_block>, <item:extendedcrafting:flux_star_block>, <item:extendedcrafting:flux_star_block>, <item:botania:gaia_ingot>, <item:mekanism:hdpe_elytra>.withTag({Damage: 0 as int}), <item:botania:gaia_ingot>, <item:extendedcrafting:flux_star_block>, <item:extendedcrafting:flux_star_block>, <item:extendedcrafting:flux_star_block>], 
	[<item:extendedcrafting:ender_star_block>, <item:occultism:otherworld_essence>, <item:occultism:otherworld_essence>, <item:botania:gaia_ingot>, <item:botania:gaia_ingot>, <item:botania:gaia_ingot>, <item:occultism:otherworld_essence>, <item:occultism:otherworld_essence>, <item:extendedcrafting:ender_star_block>], 
	[<item:extendedcrafting:ender_star_block>, <item:advanced_ae:shattered_singularity>, <item:botania:terrasteel_block>, <item:occultism:otherworld_essence>, <item:extendedcrafting:flux_star_block>, <item:occultism:otherworld_essence>, <item:botania:terrasteel_block>, <item:advanced_ae:shattered_singularity>, <item:extendedcrafting:ender_star_block>], 
	[<item:ae2:singularity>, <item:botania:terrasteel_block>, <item:advanced_ae:shattered_singularity>, <item:occultism:otherworld_essence>, <item:extendedcrafting:flux_star_block>, <item:occultism:otherworld_essence>, <item:advanced_ae:shattered_singularity>, <item:botania:terrasteel_block>, <item:ae2:singularity>], 
	[<item:botania:terrasteel_block>, <item:ae2:singularity>, <item:extendedcrafting:ender_star_block>, <item:extendedcrafting:ender_star_block>, <item:extendedcrafting:flux_star_block>, <item:extendedcrafting:ender_star_block>, <item:extendedcrafting:ender_star_block>, <item:ae2:singularity>, <item:botania:terrasteel_block>]
]);

mods.extendedcrafting.TableCrafting.addShaped("mekasuit_helmet", 4, <item:mekanism:mekasuit_helmet>, [
	[<item:extendedcrafting:ultimate_singularity>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:draconicevolution:dragon_heart>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:extendedcrafting:ultimate_singularity>], 
	[<item:mekanism:pellet_plutonium>, <item:advanced_ae:quantum_alloy_plate>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:advanced_ae:quantum_alloy_plate>, <item:mekanism:pellet_plutonium>], 
	[<item:mekanism:pellet_plutonium>, <item:mekanism:pellet_polonium>, <item:mythicbotany:alfsteel_block>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mythicbotany:alfsteel_block>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_plutonium>], 
	[<item:mekanism:pellet_plutonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mythicbotany:alfsteel_helmet>.withTag({Damage: 0 as int}), <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_plutonium>], 
	[<item:draconicevolution:dragon_heart>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_antimatter>, <item:forbidden_arcanus:tyr_helmet>.withTag({Damage: 0 as int}), <item:advanced_ae:quantum_helmet>.withTag({Damage: 0 as int, internalCurrentPower: 2.0E8 as double}), <item:mysticaladaptations:insanium_helmet>.withTag({Damage: 0 as int}), <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_polonium>, <item:draconicevolution:dragon_heart>], 
	[<item:mekanism:pellet_plutonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:bloodmagic:livinghelmet>.withTag({Damage: 0 as int}), <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_plutonium>], 
	[<item:mekanism:pellet_plutonium>, <item:mekanism:pellet_polonium>, <item:mythicbotany:alfsteel_block>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mythicbotany:alfsteel_block>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_plutonium>], 
	[<item:mekanism:pellet_plutonium>, <item:advanced_ae:quantum_alloy_plate>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:advanced_ae:quantum_alloy_plate>, <item:mekanism:pellet_plutonium>], 
	[<item:extendedcrafting:ultimate_singularity>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:draconicevolution:dragon_heart>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:extendedcrafting:ultimate_singularity>]
]);

mods.extendedcrafting.TableCrafting.addShaped("mekasuit_bodyarmor", 4, <item:mekanism:mekasuit_bodyarmor>, [
	[<item:extendedcrafting:ultimate_singularity>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:draconicevolution:dragon_heart>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:extendedcrafting:ultimate_singularity>], 
	[<item:mekanism:pellet_plutonium>, <item:advanced_ae:quantum_alloy_plate>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:advanced_ae:quantum_alloy_plate>, <item:mekanism:pellet_plutonium>], 
	[<item:mekanism:pellet_plutonium>, <item:mekanism:pellet_polonium>, <item:mythicbotany:alfsteel_block>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mythicbotany:alfsteel_block>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_plutonium>], 
	[<item:mekanism:pellet_plutonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mythicbotany:alfsteel_chestplate>.withTag({Damage: 0 as int}), <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_plutonium>], 
	[<item:draconicevolution:dragon_heart>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_antimatter>, <item:forbidden_arcanus:tyr_chestplate>.withTag({Damage: 0 as int}), <item:advanced_ae:quantum_chestplate>.withTag({Damage: 0 as int, internalCurrentPower: 3.0E8 as double}), <item:mysticaladaptations:insanium_chestplate>.withTag({Damage: 0 as int}), <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_polonium>, <item:draconicevolution:dragon_heart>], 
	[<item:mekanism:pellet_plutonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:bloodmagic:livingplate>.withTag({Damage: 0 as int, livingStats: {maxPoints: 100 as int, upgrades: []}}), <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_plutonium>], 
	[<item:mekanism:pellet_plutonium>, <item:mekanism:pellet_polonium>, <item:mythicbotany:alfsteel_block>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mythicbotany:alfsteel_block>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_plutonium>], 
	[<item:mekanism:pellet_plutonium>, <item:advanced_ae:quantum_alloy_plate>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:advanced_ae:quantum_alloy_plate>, <item:mekanism:pellet_plutonium>], 
	[<item:extendedcrafting:ultimate_singularity>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:draconicevolution:dragon_heart>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:extendedcrafting:ultimate_singularity>]
]);

mods.extendedcrafting.TableCrafting.addShaped("mekasuit_leggins", 4, <item:mekanism:mekasuit_pants>, [
	[<item:extendedcrafting:ultimate_singularity>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:draconicevolution:dragon_heart>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:extendedcrafting:ultimate_singularity>], 
	[<item:mekanism:pellet_plutonium>, <item:advanced_ae:quantum_alloy_plate>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:advanced_ae:quantum_alloy_plate>, <item:mekanism:pellet_plutonium>], 
	[<item:mekanism:pellet_plutonium>, <item:mekanism:pellet_polonium>, <item:mythicbotany:alfsteel_block>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mythicbotany:alfsteel_block>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_plutonium>], 
	[<item:mekanism:pellet_plutonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mythicbotany:alfsteel_leggings>.withTag({Damage: 0 as int}), <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_plutonium>], 
	[<item:draconicevolution:dragon_heart>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_antimatter>, <item:forbidden_arcanus:tyr_leggings>.withTag({Damage: 0 as int}), <item:advanced_ae:quantum_leggings>.withTag({Damage: 0 as int, internalCurrentPower: 2.5E8 as double}), <item:mysticaladaptations:insanium_leggings>.withTag({Damage: 0 as int}), <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_polonium>, <item:draconicevolution:dragon_heart>], 
	[<item:mekanism:pellet_plutonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:bloodmagic:livingleggings>.withTag({Damage: 0 as int}), <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_plutonium>], 
	[<item:mekanism:pellet_plutonium>, <item:mekanism:pellet_polonium>, <item:mythicbotany:alfsteel_block>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mythicbotany:alfsteel_block>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_plutonium>], 
	[<item:mekanism:pellet_plutonium>, <item:advanced_ae:quantum_alloy_plate>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:advanced_ae:quantum_alloy_plate>, <item:mekanism:pellet_plutonium>], 
	[<item:extendedcrafting:ultimate_singularity>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:draconicevolution:dragon_heart>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:extendedcrafting:ultimate_singularity>]
]);

mods.extendedcrafting.TableCrafting.addShaped("mekasuit_boots", 4, <item:mekanism:mekasuit_boots>, [
	[<item:extendedcrafting:ultimate_singularity>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:draconicevolution:dragon_heart>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:extendedcrafting:ultimate_singularity>], 
	[<item:mekanism:pellet_plutonium>, <item:advanced_ae:quantum_alloy_plate>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:advanced_ae:quantum_alloy_plate>, <item:mekanism:pellet_plutonium>], 
	[<item:mekanism:pellet_plutonium>, <item:mekanism:pellet_polonium>, <item:mythicbotany:alfsteel_block>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mythicbotany:alfsteel_block>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_plutonium>], 
	[<item:mekanism:pellet_plutonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mythicbotany:alfsteel_boots>.withTag({Damage: 0 as int}), <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_plutonium>], 
	[<item:draconicevolution:dragon_heart>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_antimatter>, <item:forbidden_arcanus:tyr_boots>.withTag({Damage: 0 as int}), <item:advanced_ae:quantum_boots>.withTag({Damage: 0 as int, internalCurrentPower: 2.0E8 as double}), <item:mysticaladaptations:insanium_boots>.withTag({Damage: 0 as int}), <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_polonium>, <item:draconicevolution:dragon_heart>], 
	[<item:mekanism:pellet_plutonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:bloodmagic:livingboots>.withTag({Damage: 0 as int}), <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_plutonium>], 
	[<item:mekanism:pellet_plutonium>, <item:mekanism:pellet_polonium>, <item:mythicbotany:alfsteel_block>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mythicbotany:alfsteel_block>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_plutonium>], 
	[<item:mekanism:pellet_plutonium>, <item:advanced_ae:quantum_alloy_plate>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:mekanism:pellet_polonium>, <item:advanced_ae:quantum_alloy_plate>, <item:mekanism:pellet_plutonium>], 
	[<item:extendedcrafting:ultimate_singularity>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:draconicevolution:dragon_heart>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:mekanism:pellet_plutonium>, <item:extendedcrafting:ultimate_singularity>]
]);

mods.extendedcrafting.TableCrafting.addShaped("chaos_heart", 4, <item:draconicadditions:chaos_heart>, [
	[<item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:ultimate_singularity>, <item:draconicevolution:chaotic_core>, <item:draconicevolution:chaotic_core>, <item:draconicevolution:chaotic_core>, <item:draconicevolution:chaotic_core>, <item:draconicevolution:chaotic_core>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:ultimate_singularity>], 
	[<item:extendedcrafting:ultimate_singularity>, <item:draconicevolution:dragon_heart>, <item:mythicbotany:fimbultyr_tablet>, <item:mekanism:creative_fluid_tank>, <item:megacells:item_storage_cell_256m>, <item:mekanism:creative_chemical_tank>, <item:mythicbotany:fimbultyr_tablet>, <item:draconicevolution:dragon_heart>, <item:extendedcrafting:ultimate_singularity>], 
	[<item:draconicevolution:chaotic_core>, <item:mythicbotany:fimbultyr_tablet>, <item:draconicevolution:dragon_heart>, <item:extendedcrafting:the_ultimate_block>, <item:extendedcrafting:the_ultimate_block>, <item:extendedcrafting:the_ultimate_block>, <item:draconicevolution:dragon_heart>, <item:mythicbotany:fimbultyr_tablet>, <item:draconicevolution:chaotic_core>], 
	[<item:draconicevolution:chaotic_core>, <item:mythicbotany:mjoellnir>, <item:extendedcrafting:the_ultimate_block>, <item:extendedcrafting:the_ultimate_block>, <item:extendedcrafting:the_ultimate_block>, <item:extendedcrafting:the_ultimate_block>, <item:extendedcrafting:the_ultimate_block>, <item:occultism:miner_marid_master>.withTag({spiritName: "Styrcresarc", rollsPerOperation: 1 as int, Damage: 0 as int, maxMiningTime: 100 as int}), <item:draconicevolution:chaotic_core>], 
	[<item:draconicevolution:chaotic_core>, <item:megacells:item_storage_cell_256m>, <item:extendedcrafting:the_ultimate_block>, <item:extendedcrafting:the_ultimate_block>, <item:draconicevolution:dragon_heart>, <item:extendedcrafting:the_ultimate_block>, <item:extendedcrafting:the_ultimate_block>, <item:megacells:item_storage_cell_256m>, <item:draconicevolution:chaotic_core>], 
	[<item:draconicevolution:chaotic_core>, <item:mythicbotany:mjoellnir>, <item:extendedcrafting:the_ultimate_block>, <item:extendedcrafting:the_ultimate_block>, <item:extendedcrafting:the_ultimate_block>, <item:extendedcrafting:the_ultimate_block>, <item:extendedcrafting:the_ultimate_block>, <item:occultism:miner_marid_master>.withTag({spiritName: "Styrcresarc", rollsPerOperation: 1 as int, Damage: 0 as int, maxMiningTime: 100 as int}), <item:draconicevolution:chaotic_core>], 
	[<item:draconicevolution:chaotic_core>, <item:mythicbotany:fimbultyr_tablet>, <item:draconicevolution:dragon_heart>, <item:extendedcrafting:the_ultimate_block>, <item:extendedcrafting:the_ultimate_block>, <item:extendedcrafting:the_ultimate_block>, <item:draconicevolution:dragon_heart>, <item:mythicbotany:fimbultyr_tablet>, <item:draconicevolution:chaotic_core>], 
	[<item:extendedcrafting:ultimate_singularity>, <item:draconicevolution:dragon_heart>, <item:mythicbotany:fimbultyr_tablet>, <item:botania:creative_pool>, <item:megacells:item_storage_cell_256m>, <item:botania:mana_tablet>.withTag({mana: 500000 as int, creative: 1 as byte}), <item:mythicbotany:fimbultyr_tablet>, <item:draconicevolution:dragon_heart>, <item:extendedcrafting:ultimate_singularity>], 
	[<item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:ultimate_singularity>, <item:draconicevolution:chaotic_core>, <item:draconicevolution:chaotic_core>, <item:draconicevolution:chaotic_core>, <item:draconicevolution:chaotic_core>, <item:draconicevolution:chaotic_core>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:ultimate_singularity>]
]);