craftingTable.remove(<item:draconicevolution:basic_crafting_injector>);
craftingTable.remove(<item:angelring:angel_ring>);
craftingTable.remove(<item:angelring:diamond_ring>);
craftingTable.remove(<item:mekanism:robit>);
craftingTable.remove(<item:mekanism:robit>.withTag({mekData: {EnergyContainers: [{Container: 0, stored: "100000"}]}}));
craftingTable.remove(<item:mekanism:mekasuit_helmet>);
craftingTable.remove(<item:mekanism:mekasuit_bodyarmor>);
craftingTable.remove(<item:mekanism:mekasuit_pants>);
craftingTable.remove(<item:mekanism:mekasuit_boots>);
craftingTable.remove(<item:mekanism:cardboard_box>);